002 unit test basic functionality
redbadger/work_editor pull request #3
Opened 2021-09-24 09:51 UTC by Francesca-E

2021-09-24 15:40 UTC, jameshopkins requested changes
Not a blocker now, but I think it would be worth removing the mutations on a couple of the functions dealing with data structures, like we did with `handleRemoveItem()` earlier.

2021-09-24 15:40 UTC, jameshopkins commented on pages/index.test.js
> +  expect(updateBoard).toBeCalled();
I reckon, like the other tests, we should assert that the argument to `updateBoard` should be of a certain structure

2021-09-24 16:04 UTC, jameshopkins commented on pages/index.test.js
> +  expect(updateBoard).toBeCalled();
Ignore this. The creation of the ID here will eventually be replaced by the result of the DB record creation, so I wouldn't worry about it for now 👍

2021-09-24 16:04 UTC, jameshopkins approved these changes

2021-09-27 08:46 UTC, ruiramos approved these changes
Looks great, well done! Love what you're doing with passing all the functions the handlers need, it makes it really easy to test and change the internal behaviour in the future.

2021-09-27 08:47 UTC, ruiramos commented on pages/index.test.js
> +  expect(updateBoard).toBeCalled();
You could maybe expect the length of the backlog board to have increased by 1?

2021-09-27 09:22 UTC, merged